secrets:
  influx:
    enabled: false
    name: influx
    ## Set secket keys if needed
    # dbKey: influx-db
    # urlKey: influx-url
    # userKey: influx-user
    # passKey: influx-pass
  github:
    enabled: false
    name: github
    ## Set secket keys if needed
    # userKey: github-user
    # tokenKey: github-token
    # orgKey: github-org
    # repoKey: github-repo
  telemetry:
    enabled: false
    name: telemetry
    ## Set secket keys if needed
    # accessKey: telemetry-access-key
    # secretKey: telemetry-secret-key
    # urlKey: telemetry_url

## Set the kind of metrics to collect: catalog, github and telemetry are supported
kind: github
## Set collector image by kind
# image: rawmind/rancher-catalog-stats:0.3-3
# image: rawmind/github-metrics:0.0.4-amd64
# image: rawmind/rancher-telemetry-stats:0.2-11
image: rawmind/github-metrics:0.0.4-amd64
pullPolicy: IfNotPresent
volumeMounts: []
## Metrics arg by kind
# catalog   https://github.com/rawmind0/rancher-catalog-stats#usage
# github    https://github.com/rawmind0/github-metrics#usage
# telemetry https://github.com/rawmind0/rancher-telemetry-stats#usage
args: []

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi

## Node labels for pod assignment https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/
nodeSelector: {}

## Tolerations for pod assignment https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
tolerations: []

## Affinity for pod assignment https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
affinity: {}

## Volumes for pod https://kubernetes.io/docs/concepts/storage/volumes/
volumes: []
