apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opdom.dbName" . }}
  labels:
    {{- include "opdom.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
type: Opaque
data:
  {{ $secret := (lookup "v1" "Secret" .Release.Namespace "db") }}
  user: {{ "opdom" | b64enc | quote }}
  {{ if (($secret.data).pass) }}
  pass: {{ $secret.data.pass | quote }}
  {{ else }}
  pass: {{ randAlphaNum 16 | b64enc | quote }}
  {{ end }}
