apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opdom.serverName" . }}
  labels:
    {{- include "opdom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  config.json: |
    {
      "global": {
        "secret_key": {{ required "a jwt signing key is required" .Values.server.secretKey | quote }}
      },
      "database": {
        "user": {{ .Values.db.username | default "opdom" | quote }},
        "pass": {{ .Values.db.password | default "opdom" | quote }},
        "host": {{ .Values.db.hostname | default include "opdom.dbName" . | quote }},
        "port": {{ .Values.db.port | default "3306" | quote }},
        "name": {{ .Values.db.name | default "opdom" | quote }},
      },
      "github": {
        "client_id": {{ .Values.github.clientId | quote }},
        "client_secret": {{ .Values.github.clientSecret | quote }}
      },
      "http": {
        "port": "80"
      }
    }
