apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}
  labels:
    {{- include "opdom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
type: Opaque
stringData:
  config.json: |
    {
      "global": {
        "secret_key": {{ required "a jwt signing key is required" .Values.app.secretKey | quote }}
      },
      "database": {
        "user": {{ .Values.app.dbConnection.username | quote }},
        "pass": {{ .Values.app.dbConnection.password | quote }},
        "host": {{ .Values.app.dbConnection.host | quote }},
        "port": {{ .Values.app.dbConnection.port | quote }},
        "name": {{ .Values.app.dbConnection.name | quote }}
      },
      "github": {
        "client_id": {{ .Values.github.clientId | quote }},
        "client_secret": {{ .Values.github.clientSecret | quote }}
      },
      "http": {
        "port": "80"
      }
    }
