apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opdom.name" . }}
  labels:
    {{- include "opdom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      {{- include "opdom.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: server
  template:
    metadata:
      {{- with .Values.app.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "opdom.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: server
    spec:
      volumes:
      - name: config
        secret:
          secretName: {{ include "opdom.name" . }}
      containers:
        - name: opdom
          volumeMounts:
          - name: config
            mountPath: /opt/opdom
          image: "{{ .Values.app.image.repository }}:{{ .Values.app.image.tag }}"
          imagePullPolicy: {{ .Values.app.image.pullPolicy }}
          command:
            - ./bin/opdom
            - -c
            - /opt/opdom/config.json
          ports:
            - name: http
              containerPort: {{ .Values.app.port }}
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
