apiVersion: v1
kind: Service
metadata:
  name: {{ include "opdom.serverName" . }}
  labels:
    {{- include "opdom.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "opdom.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: server
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: http
      protocol: TCP
      name: http
