applicationName: opni-upgrade-responder

secret:
  name: opni-upgrade-responder-secrets
  managed: false
  influxDBUrl: ""
  influxDBUser: ""
  influxDBPassword: ""

configMap:
  responseConfig: |-
    {
       "Versions": [{
          "Name": "v0.3.0",
          "ReleaseDate": "2021-12-11T20:30:00Z",
          "Tags": ["latest"]
       }]
    }

replicaCount: 3

image:
  repository: longhornio/upgrade-responder
  tag: v0.1.2
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 8314

ingress:
  enabled: true
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "10254"
  path: /
  hosts:
    - opni-upgrade-responder.rancher.io
  tls:
   - secretName: opni-upgrade-responder-rancher-io-tls
     hosts:
       - opni-upgrade-responder.rancher.io

resources:
  limits:
   cpu: 200m
   memory: 256Mi
  requests:
   cpu: 100m
   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

