apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-collector-query-params 
  labels:
    {{- include "metrics-collector.labels" . | nindent 4 }}
data:
  hours: {{ .Values.configmaps.query_params.hours | quote | indent 2 }}
  refresh: {{ .Values.configmaps.query_params.refresh | quote | indent 2 }}
